#!/bin/bash
# Install the repo's local git hooks.
#
# There is no CI here and no remote configured, so the agent-config validators only ever ran
# when a human remembered — which meant adding validators had limited value. This wires them
# to the one event that always happens before work is recorded.
#
# Idempotent. Run from anywhere: `bash .agents/scripts/install-git-hooks.sh`
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
hook_dir="$root/.git/hooks"

if [ ! -d "$hook_dir" ]; then
  echo "no .git/hooks at $hook_dir — not a git repository?" >&2
  exit 1
fi

cat > "$hook_dir/pre-commit" <<'HOOK'
#!/bin/bash
# Generated by .agents/scripts/install-git-hooks.sh — re-run that to update.
set -eu
root=$(git rev-parse --show-toplevel)

# Only guard the shared agent configuration; a commit touching nothing else skips instantly.
if git diff --cached --name-only | grep -qE '^\.(agents|claude|codex)/'; then
  echo "pre-commit: validating agent config…"
  node "$root/.agents/scripts/validate-agent-config.mjs" || {
    echo "pre-commit: agent config invalid — fix it, or commit with --no-verify only if you" >&2
    echo "            have a reason the policy itself does not cover." >&2
    exit 1
  }
  node "$root/.agents/scripts/test-agent-config.mjs" || exit 1
fi

# Plan and cycle-note YAML changes get the docs-gen schema check, when its deps are present.
if git diff --cached --name-only | grep -qE '^projects/.*/docs/.*\.ya?ml$'; then
  if [ -d "$root/tools/docs-gen/node_modules" ]; then
    ( cd "$root/tools/docs-gen" && npm run validate --silent ) || exit 1
  else
    echo "pre-commit: skipping YAML validation — run 'npm i' in tools/docs-gen/ to enable" >&2
  fi
fi
HOOK

chmod +x "$hook_dir/pre-commit"
echo "installed $hook_dir/pre-commit"
