#!/bin/bash
# Install the repo's local git hooks — in the root repo AND in every nested project repo.
#
# There is no CI here and no remote configured, so the agent-config validators only ever ran
# when a human remembered — which meant adding validators had limited value. This wires them
# to the one event that always happens before work is recorded.
#
# Two hooks are installed per repo:
#   pre-commit — the config / docs-YAML validators (root and nested variants).
#   pre-push   — the destructive-remote gate. It lives here, not in the PreToolUse command
#                matcher, because git resolves refs BEFORE calling pre-push and hands the
#                resolved SHAs over on stdin. Measured against the command gate before this
#                change: `git push origin +main`, `git push --mirror origin`,
#                `git push origin :main` and `git push --delete origin main` all returned
#                rc=0 — four destructive pushes waved through, because textually they are
#                indistinguishable from a plain push. At the ref boundary they are two SHA
#                comparisons and nothing has to be parsed.
#
# The nested variant exists because the root hook's YAML arm was unreachable: `/projects/` is
# .gitignore:3, so `git ls-files projects/` returns 0 and no staged path in the root repo can
# ever start with `projects/`. Every plan-NNN.yaml and cycle note actually commits inside its
# own nested repo, where paths are repo-relative ("docs/plan-001.yaml") — that is where the
# gate has to live. Measured before this change: 0 of 6 nested repos had a pre-commit hook,
# so 130 valid cycle notes were discipline, not enforcement.
#
# Idempotent, and it will not clobber a hook it did not write. Run from anywhere:
#   bash .agents/scripts/install-git-hooks.sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)

# Every generated hook carries this line; install_hook uses it to tell "mine, safe to replace"
# from "someone else's, hands off".
MARKER='# Generated by .agents/scripts/install-git-hooks.sh'

# ------------------------------------------------------------------
# hook bodies
#
# Read with `read -r -d ''`, not `body=$(cat <<'HOOK' … HOOK)`: macOS ships bash 3.2, whose
# `$( )` scanner mis-parses a `case … ;;` inside a quoted heredoc and dies with
# "syntax error near unexpected token `;;'" on a line it should never have parsed. `read`
# keeps the heredoc's trailing newline, so install_hook writes bodies with `printf '%s'`.
# ------------------------------------------------------------------

IFS= read -r -d '' root_body <<'HOOK' || true
#!/bin/bash
# Generated by .agents/scripts/install-git-hooks.sh — re-run that to update.
set -eu
root=$(git rev-parse --show-toplevel)

# Only guard the shared agent configuration; a commit touching nothing else skips instantly.
if git diff --cached --name-only | grep -qE '^\.(agents|claude|codex)/'; then
  echo "pre-commit: validating agent config…"
  node "$root/.agents/scripts/validate-agent-config.mjs" || {
    echo "pre-commit: agent config invalid — fix it, or commit with --no-verify only if you" >&2
    echo "            have a reason the policy itself does not cover." >&2
    exit 1
  }
  node "$root/.agents/scripts/test-agent-config.mjs" || exit 1

  # The push gate is generated by install-git-hooks.sh and lives nowhere test-agent-config.mjs
  # looks — `grep -c pre-push .agents/scripts/test-agent-config.mjs` was 0, so the entire hook
  # body could be replaced with `exit 0` and the suite above still went green. This is the arm
  # that would have caught it. ~5s: it builds throwaway repo pairs under $TMPDIR and drives
  # real pushes through the hook the installer emits.
  bash "$root/.agents/scripts/test-git-hooks.sh" || {
    echo "pre-commit: the pre-push gate failed its own tests — see above." >&2
    echo "            .agents/scripts/test-git-hooks.sh reproduces it." >&2
    exit 1
  }

  # Same argument, one gate over: the PreToolUse(Edit|Write|NotebookEdit) git-internals write
  # policy is what stops an agent hand-editing `.git/config` (core.hooksPath) or `.git/hooks/*`
  # — i.e. switching the pre-push gate above OFF without running a single git command. It
  # shipped with a full suite that nothing invoked: `grep -c test-git-internals
  # .agents/scripts/install-git-hooks.sh` was 0, so the policy could be deleted outright and
  # every gate still reported green. This is the arm that runs it. Like the push-gate suite it
  # is a PROCESS-contract test — real payloads through the real wrapper into the real policy —
  # which is why it lives here and not in test-agent-config.mjs.
  #
  # python3 is its only prerequisite (the policy is Python and the harness builds its payloads
  # with it). A missing interpreter is an environment state, not a policy violation, so it
  # skips loudly and never blocks — the same shape as the nested hook's node_modules arm.
  if command -v python3 >/dev/null 2>&1; then
    bash "$root/.agents/scripts/test-git-internals-hook.sh" || {
      echo "pre-commit: the git-internals write gate failed its own tests — see above." >&2
      echo "            .agents/scripts/test-git-internals-hook.sh reproduces it." >&2
      exit 1
    }
  else
    echo "pre-commit: skipping git-internals gate tests — python3 is not on PATH" >&2
  fi
fi

# No docs-YAML arm here on purpose. The root repo tracks zero .yaml/.yml files
# (`git ls-files '*.yaml' '*.yml'` → 0) and `/projects/` is .gitignore:3, so the old
# `^projects/.*/docs/.*\.ya?ml$` arm could not match any staged path and never fired once.
# That check now lives in the nested-repo hook, where those files are actually staged.
HOOK

IFS= read -r -d '' nested_body <<'HOOK' || true
#!/bin/bash
# Generated by .agents/scripts/install-git-hooks.sh — re-run that to update.
#
# Nested-repo variant: the docs-YAML gate. Plan and cycle-note YAML commits HERE, never in the
# root repo — `/projects/` is .gitignore:3 up there, which is why the root hook's
# `^projects/.*/docs/.*\.ya?ml$` arm could never match: paths are repo-relative in this repo.
# The validators live in the root repo (a nested repo has no tools/docs-gen), so the root path
# is baked in at install time and they are invoked absolutely.
set -eu

root='@@ROOT@@'
gen="$root/tools/docs-gen"
cd "$(git rev-parse --show-toplevel)"

# --diff-filter=d: a commit that DELETES a plan or cycle note must not try to validate a file
# that is no longer on disk (same class of bug as the exemption check for deleted files).
staged=$(git diff --cached --name-only --diff-filter=d | grep -E '^docs/.*\.ya?ml$' || true)
[ -n "$staged" ] || exit 0

# Missing deps are an environment state, not a policy violation: skip loudly, never block.
if [ ! -d "$gen/node_modules" ]; then
  echo "pre-commit: skipping docs YAML validation — run 'npm i' in $gen to enable" >&2
  exit 0
fi

# Validate the STAGED blob, not the working-tree file: `git add` followed by an edit would
# otherwise wave broken YAML into the commit on the strength of a fixed working copy. The
# temp tree mirrors the repo-relative path so basenames survive (validate-cycle-note.mjs
# cross-checks the filename against the `cycle:` field) and error output stays readable.
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
plans=()
notes=()
while IFS= read -r f; do
  [ -n "$f" ] || continue
  copy="$tmp/$f"
  mkdir -p "$(dirname "$copy")"
  git show ":$f" > "$copy"
  case "$f" in
    docs/cycles/*)      notes+=("$copy") ;;
    docs/plan-*.yaml|docs/plan-*.yml) plans+=("$copy") ;;
    # Any other docs/*.yaml has no schema in docs-gen — nothing to check it against.
  esac
done <<< "$staged"

status=0

if [ "${#plans[@]}" -gt 0 ]; then
  echo "pre-commit: validating plan YAML…"
  node --input-type=module -e '
const [lib, tmp, ...files] = process.argv.slice(1);
const { validateFile } = await import(lib);
let bad = 0;
for (const f of files) {
  const label = f.slice(tmp.length + 1);
  try { validateFile(f, label); console.log(`  ✓ ${label}`); }
  catch (e) { bad++; console.error(`\n${e.message}\n`); }
}
process.exit(bad ? 1 : 0);
' "file://$gen/lib/validate-source.mjs" "$tmp" "${plans[@]}" || status=1
fi

if [ "${#notes[@]}" -gt 0 ]; then
  echo "pre-commit: validating cycle notes…"
  # That validator prints the path it was handed, which here is the staged-blob copy. Strip the
  # temp prefix so the report names the file the author actually has to open.
  out=$(node "$gen/scripts/validate-cycle-note.mjs" "${notes[@]}" 2>&1) || status=1
  printf '%s\n' "$out" | sed "s|$tmp/||g"
fi

if [ "$status" -ne 0 ]; then
  echo "pre-commit: docs YAML invalid — fix it, or commit with --no-verify only if you" >&2
  echo "            have a reason the policy itself does not cover." >&2
  exit 1
fi
HOOK

IFS= read -r -d '' push_body <<'HOOK' || true
#!/bin/bash
# Generated by .agents/scripts/install-git-hooks.sh — re-run that to update.
#
# pre-push: the destructive-remote gate for .agents/rules/cycle-orchestration.md
# ("Never, even when authorized" → force pushes).
#
# git invokes this as:  pre-push <remote-name> <remote-url>
# and feeds one line per ref on stdin:
#   <local_ref> <local_sha> <remote_ref> <remote_sha>
#
# Both SHAs are already RESOLVED by git, which is the whole reason the check belongs here.
# A command-line matcher has to recognise every spelling of "destroy the remote" —
# `--force`, `--force-with-lease`, `-f`, `+refspec`, `--mirror`, `:branch`, `--delete`, `-d`,
# a push.default / remote.*.push config that quietly expands to a forced refspec, or any of
# those reached through an exec wrapper. That is an open set, and it lost. Here it is:
#   local_sha  == 0*  → deletion
#   remote_sha != 0*  and not an ancestor of local_sha → the remote loses commits
# which is the actual definition of the thing being banned, with no parsing at all.
#
# Deliberately NOT blocked: an ordinary fast-forward push. Pushing zulfahmi-portfolio to
# main is what deploys zulfahmi.dev, and the rule leaves plain push open on purpose.
#
# What this hook structurally CANNOT cover, and so stays in the PreToolUse command gate:
# `--amend` (never reaches a push) and `--no-verify` (git skips this hook entirely, so a
# hook can never defend itself against it).
#
# No path is ever resolved relative to $PWD and nothing cd's: git exports GIT_DIR for hooks,
# and a `cd` here would break the common case where that export is the relative string ".git".
#
# --dry-run is NOT distinguishable here, and is therefore refused along with the real thing.
# Measured (git 2.54.0, macOS) by tracing a hook that dumped argv, stdin and env for each:
#   git push --dry-run origin main   → argv "origin <url>"; stdin
#                                      "refs/heads/main <new> refs/heads/main <old>"
#   git push origin main             → byte-identical argv and stdin
# and for a dry-run force and a dry-run delete likewise: the stdin line is the same one the
# real push sends. `git help githooks` documents argv and the four stdin fields and says
# nothing about dry runs. GIT_PUSH_OPTION_* is a receive-side variable — `git push -o …`
# exports nothing into pre-push (verified: the env dump was unchanged, and the local
# transport rejected the option outright). The only place the string "--dry-run" survives is
# the parent process's argv, and reading that would (a) reintroduce exactly the command-line
# parsing this hook exists to avoid, (b) trust a value the caller controls, and (c) break the
# moment git is invoked through a wrapper. So a dry run of a forbidden push is refused. That
# is a false positive on a command that would have written nothing — accepted deliberately,
# because the alternative is an env var or flag that a real destructive push can also set.
# Do not "fix" it by sniffing the parent command line.
set -euo pipefail

remote_name=${1:-<unnamed remote>}
remote_url=${2:-<unknown url>}

# ------------------------------------------------------------------
# 0. MIRROR-CONFIGURED REMOTE — checked BEFORE stdin is read, because this case can send
#    zero stdin lines and still delete branches.
#
#    `git clone --mirror` sets remote.origin.mirror=true, which makes a bare `git push origin`
#    a full mirror push including the prune half. Measured against a real clone --mirror pair:
#    with refs/heads/doomed present upstream and deleted locally, `git push origin` fed this
#    hook 0 (zero) stdin lines and deleted refs/heads/doomed on the remote. There is no ref
#    line to inspect, so no per-line rule can ever catch it; the configuration itself is the
#    only evidence, and git hands us the remote's name in $1.
# ------------------------------------------------------------------
mirror_cfg=$(git config --get --bool "remote.$remote_name.mirror" 2>/dev/null || true)
if [ -z "$mirror_cfg" ]; then
  # --bool exits non-zero both when the key is unset and when its value is not a boolean.
  # A key that is set to something unparseable is not "off" — treat any value as mirror-on.
  mirror_raw=$(git config --get "remote.$remote_name.mirror" 2>/dev/null || true)
  [ -z "$mirror_raw" ] || mirror_cfg=true
fi
if [ "$mirror_cfg" = true ]; then
  printf 'pre-push: BLOCKED — remote "%s" is configured as a mirror (remote.%s.mirror).\n' \
    "$remote_name" "$remote_name" >&2
  printf '          In a --mirror clone a plain `git push %s` IS a mirror push: it force-\n' "$remote_name" >&2
  printf '          updates every ref AND deletes every remote ref this repo lacks. git\n' >&2
  printf '          reports none of those deletions on this hook stdin (measured: 0 lines\n' >&2
  printf '          while a remote branch was removed), so the push is refused whole.\n' >&2
  printf '          To push one branch from a mirror clone, name it explicitly against a\n' >&2
  printf '          non-mirror remote.\n' >&2
  printf '\npre-push: refusing to push to "%s" (%s).\n' "$remote_name" "$remote_url" >&2
  exit 1
fi

# All-zero SHA without hardcoding a width — sha1 repos send 40 zeros, sha256 repos send 64.
# The empty case is rejected first on purpose: `*[!0]*` does not match an empty string
# either, so without this guard a truncated stdin line would read as "deletion".
is_zero() {
  [ -n "${1:-}" ] || return 1
  case "$1" in
    *[!0]*) return 1 ;;
    *)      return 0 ;;
  esac
}

blocked=0

# stdin is the ref list, so the loop is NOT in a pipeline — `blocked` has to survive each
# iteration. Every git call inside redirects </dev/null so it cannot eat the ref list.
#
# `|| [ -n "$local_ref" ]` is load-bearing, not defensive noise. `read` returns non-zero when
# it hits EOF without a delimiter, i.e. on a final line with no trailing newline — it still
# ASSIGNS the fields, but the plain `while read …; do` form throws that iteration away, so the
# line never reaches the loop body and not even the malformed-line branch below fires.
# Measured against the previous revision of this hook: a single unterminated
# "refs/heads/main <sha> refs/heads/main deadbeef…" line (an unverifiable remote tip, which
# must fail closed) returned rc=0, and so did an unterminated "(delete) 000… " line. Both are
# rc=1 with this guard. git itself terminates every line today; this hook is also invoked
# directly by its tests and by anything else that pipes it a ref list, and "the producer
# always ends with \n" is not something a gate gets to assume.
while read -r local_ref local_sha remote_ref remote_sha || [ -n "${local_ref:-}" ]; do
  [ -n "${local_ref:-}" ] || continue
  : "${local_sha:=}" "${remote_ref:=}" "${remote_sha:=}"

  # A short line means git's contract changed under us, or something else is feeding this
  # hook. Either way the decision below cannot be made, so refuse rather than assume.
  if [ -z "$local_sha" ] || [ -z "$remote_ref" ] || [ -z "$remote_sha" ]; then
    printf 'pre-push: BLOCKED — malformed ref line: %s\n' "$local_ref $local_sha $remote_ref $remote_sha" >&2
    printf '          Expected "<local_ref> <local_sha> <remote_ref> <remote_sha>".\n' >&2
    blocked=1
    continue
  fi

  # 1. MIRROR VIA --mirror ON THE COMMAND LINE. Its prune half is never put on this stdin:
  #    git enumerates only refs the LOCAL repo holds, so a remote-only branch is deleted
  #    without a line appearing here at all. Measured: with main non-divergent,
  #    `git push --mirror origin` returned rc=0 and deleted refs/heads/doomed while this hook
  #    saw three unrelated lines. The structural tell is that --mirror ships refs/remotes/*
  #    to the SAME path on the remote — remote-tracking refs written as remote-tracking refs,
  #    which no ordinary push ever does. Measured stdin from `git push --mirror origin`:
  #      refs/remotes/origin/main <sha> refs/remotes/origin/main 000…
  #      refs/remotes/origin/HEAD <sha> refs/remotes/origin/HEAD 000…
  #    Reject the whole push on sight of one, so the prune never happens.
  #
  #    Both sides are tested, not just local_ref. `git push origin
  #    refs/remotes/origin/main:refs/heads/backup` — snapshotting a remote-tracking ref onto
  #    a backup branch, a normal recovery move before anything risky — also has a
  #    refs/remotes/* local_ref, but its remote_ref is a plain branch and it is a CREATION.
  #    The previous revision refused it on local_ref alone. A mirror push writes
  #    refs/remotes/X → refs/remotes/X; the backup idiom writes refs/remotes/X → refs/heads/Y.
  #    Requiring the destination to be refs/remotes/* separates them exactly, and costs
  #    nothing: a push that really does aim a remote-tracking ref at refs/remotes/* on the
  #    remote is a mirror or a hand-rolled imitation of one either way. The backup push then
  #    falls through to the ordinary checks below — creation passes, and overwriting an
  #    existing refs/heads/backup non-fast-forward is still blocked by 3b.
  case "$local_ref" in
    refs/remotes/*)
      case "$remote_ref" in
        refs/remotes/*)
          printf 'pre-push: BLOCKED — mirror push (%s -> %s).\n' "$local_ref" "$remote_ref" >&2
          printf '          --mirror rewrites every remote ref AND deletes any the local repo\n' >&2
          printf '          lacks. git does not report those deletions to this hook, so the\n' >&2
          printf '          whole push is refused rather than half-checked.\n' >&2
          blocked=1
          continue
          ;;
      esac
      ;;
  esac

  # 2. DELETION — `git push origin :main`, `--delete`, `-d`, and the pruning half of
  #    `--mirror`. git sets local_ref to "(delete)" and local_sha to all zeros.
  if is_zero "$local_sha"; then
    printf 'pre-push: BLOCKED — deletion of remote ref %s\n' "${remote_ref:-<unknown>}" >&2
    printf '          Deleting a published branch or tag is not recoverable from here.\n' >&2
    blocked=1
    continue
  fi

  # A ref that does not exist on the remote yet cannot be rewritten by creating it.
  if is_zero "$remote_sha"; then
    continue
  fi

  # 3a. Ancestry is unjudgeable if the remote tip is not an object we hold — a stale or
  #     never-fetched remote-tracking ref. Fail CLOSED: "I don't know" is not "it's fine".
  if ! git cat-file -e "$remote_sha" </dev/null 2>/dev/null; then
    printf 'pre-push: BLOCKED — cannot verify %s: remote tip %s is not in this repo.\n' \
      "${remote_ref:-<unknown>}" "$remote_sha" >&2
    printf '          Run `git fetch %s` first so ancestry can be checked.\n' "$remote_name" >&2
    blocked=1
    continue
  fi

  # 3b. NON-FAST-FORWARD — the remote tip is not reachable from what is being pushed, so
  #     the push would drop commits that are already published. This is what a force push
  #     IS, however it was spelled on the command line.
  if ! git merge-base --is-ancestor "$remote_sha" "$local_sha" </dev/null 2>/dev/null; then
    printf 'pre-push: BLOCKED — non-fast-forward update of %s\n' "${remote_ref:-<unknown>}" >&2
    printf '            remote %s\n' "$remote_sha" >&2
    printf '            local  %s\n' "$local_sha" >&2
    printf '          The remote tip is not an ancestor of what you are pushing: this\n' >&2
    printf '          rewrites published history and discards commits on the remote.\n' >&2
    blocked=1
    continue
  fi

  # 4. Fast-forward — allowed, and intentionally so.
done

if [ "$blocked" -ne 0 ]; then
  printf '\npre-push: refusing to push to "%s" (%s).\n' "$remote_name" "$remote_url" >&2
  printf '          Policy: .agents/rules/cycle-orchestration.md, "Never, even when\n' >&2
  printf '          authorized" — force pushes and remote deletions. Plain fast-forward\n' >&2
  printf '          pushes are deliberately left open; rewriting or removing a ref that\n' >&2
  printf '          other checkouts and deploys already have is not an agent decision.\n' >&2
  printf '          If a human genuinely needs this, do it deliberately and by hand.\n' >&2
  exit 1
fi
HOOK

# The nested hook cannot find the root repo on its own, so bake the absolute path in.
# push_body needs no substitution — it is self-contained and identical in every repo.
nested_body=${nested_body//@@ROOT@@/$root}

# ------------------------------------------------------------------
# installer
# ------------------------------------------------------------------

# install_hook <repo-worktree> <hook-name> <body>
install_hook() {
  repo=$1
  name=$2
  body=$3

  # rev-parse --git-path resolves .git-as-a-file (worktrees, submodules) too.
  hooks=$(git -C "$repo" rev-parse --git-path hooks 2>/dev/null) || {
    echo "skipped $repo — not a git repository" >&2
    return 0
  }
  case "$hooks" in /*) ;; *) hooks="$repo/$hooks" ;; esac
  mkdir -p "$hooks"
  hook="$hooks/$name"

  # This header has claimed idempotence since day one while `cat >` overwrote unconditionally,
  # so installing into a repo that already had its own pre-commit (husky, lefthook, a
  # hand-rolled linter) destroyed it silently. Only replace hooks this script generated.
  if [ -e "$hook" ] && ! grep -qF "$MARKER" "$hook" 2>/dev/null; then
    echo "skipped $hook — existing hook was not generated by this script; leaving it alone" >&2
    echo "        move or delete it and re-run to install the shared gate." >&2
    return 0
  fi

  # Both sides through command substitution so the trailing-newline handling matches.
  if [ -e "$hook" ] && [ "$(cat "$hook")" = "$(printf '%s' "$body")" ]; then
    echo "up to date $hook"
    return 0
  fi

  printf '%s' "$body" > "$hook"
  chmod +x "$hook"
  echo "installed  $hook"
}

install_hook "$root" pre-commit "$root_body"
install_hook "$root" pre-push   "$push_body"

# A root-repo worktree has no projects/ at all — the nested repos live only in the primary
# checkout. Hard-failing here would red out every worktree (and every `git bisect` step that
# runs this), so absence is a skip, not an error.
if [ ! -d "$root/projects" ]; then
  echo "no $root/projects — skipping nested-repo hooks (root-only checkout or worktree)"
  exit 0
fi

# ------------------------------------------------------------------
# repo discovery
#
# This used to be `for candidate in "$root"/projects/*/*`, which hardcodes the assumption that
# a project's repository IS `projects/<group>/<name>`. That is only the common case. A project
# whose repos sit one level deeper — `projects/<group>/<name>/app/.git` and
# `projects/<group>/<name>/server/.git`, with `<name>` itself an ordinary directory — matched
# the glob at the `<name>` level, failed the `.git` test, and was skipped in silence. There was
# no output saying so: `found` counted only what the glob caught, so the installer reported
# success while two repos with live remotes had no push gate at all. The operator hit exactly
# that and decommissioned the project rather than the assumption.
#
# So repos are DISCOVERED by walking, not addressed by depth. The walk is bounded on four
# sides, because an unbounded walk over projects/ is a walk over every node_modules in the
# monorepo:
#   · MAX_DEPTH below projects/ — 4, so `<group>/<name>/<sub>/<sub2>` is reachable while a
#     deeply vendored tree is not.
#   · a discovered repo is a LEAF. Nothing descends into one, which is what keeps the walk off
#     `.git/` internals, off submodules, and off any repository vendored inside a project —
#     none of which are this monorepo's projects, and all of which would be surprising places
#     to find a gate installed.
#   · SKIP_DIRS: directories a project repo is never the child of. Dotted names go too, which
#     is what keeps `.claude/worktrees/` out — a worktree shares its parent's hooks directory,
#     so installing "into" one writes to a repo already covered.
#   · gitignore, asked of the nearest enclosing repository. Its one trap is the monorepo root:
#     `/projects/` is .gitignore:3 up there, so the root repo answers "ignored" for every
#     candidate under projects/ and honouring that verdict prunes the entire subtree — 6 repos
#     to 0. Measured. So the root's verdict is discarded and every other repo's is honoured.
# ------------------------------------------------------------------

MAX_DEPTH=4

skip_dir() {
  case "$1" in
    .*) return 0 ;;                                   # .git, .github, .claude/worktrees, …
    node_modules|vendor|Pods|target|__pycache__) return 0 ;;
    dist|build|out|coverage|html) return 0 ;;         # build output; `html` is docs-gen's
    *) return 1 ;;
  esac
}

# True when the nearest enclosing repository ignores this path. See the root-repo trap above.
path_is_ignored() {
  ignore_parent=$(dirname "$1")
  ignore_top=$(git -C "$ignore_parent" rev-parse --show-toplevel 2>/dev/null) || return 1
  [ "$ignore_top" = "$root" ] && return 1
  git -C "$ignore_parent" check-ignore -q "$1" 2>/dev/null
}

repos=""
discover() {
  discover_dir=$1
  discover_depth=$2
  [ "$discover_depth" -le "$MAX_DEPTH" ] || return 0
  for entry in "$discover_dir"/*; do
    [ -d "$entry" ] || continue
    # A symlinked directory is some other tree reached under a second name; following one
    # invites a cycle that only MAX_DEPTH would stop, and installs the same repo twice.
    [ -L "$entry" ] && continue
    skip_dir "${entry##*/}" && continue
    path_is_ignored "$entry" && continue
    if [ -e "$entry/.git" ]; then
      repos="$repos$entry
"
      continue
    fi
    discover "$entry" $((discover_depth + 1))
  done
}

discover "$root/projects" 1

found=0
while IFS= read -r candidate; do
  [ -n "$candidate" ] || continue
  found=$((found + 1))
  install_hook "$candidate" pre-commit "$nested_body"
  # The nested repos are the ones with live GitHub remotes — the root repo has none — so
  # this is the arm that actually matters for the push gate.
  install_hook "$candidate" pre-push   "$push_body"
done <<EOF
$repos
EOF

if [ "$found" -eq 0 ]; then
  echo "no nested git repositories under $root/projects"
fi

# The skips are REPORTED, which the glob version never did — that silence IS the bug this
# replaced. A project directory holding no repository at all is fine (northsoil-hr is one);
# a project holding a repository the walk could not REACH is the same failure again, one
# bound further out, so the two are told apart rather than both printed as "nothing to do".
# The second probe is a `find`, deliberately: it is not bound by MAX_DEPTH or SKIP_DIRS, so
# it can see precisely what the walk cannot, and it runs only for the handful of project
# directories the walk came back empty from. Depth 2 only — that is the level at which "a
# project" is a meaningful noun.
for candidate in "$root"/projects/*/*; do
  [ -d "$candidate" ] || continue
  [ -e "$candidate/.git" ] && continue
  case "$repos" in
    *"$candidate/"*) continue ;;   # its repos live deeper; already installed above
  esac
  unreached=$(find "$candidate" -maxdepth 6 -name .git -not -path '*/node_modules/*' -print 2>/dev/null | head -1)
  if [ -n "$unreached" ]; then
    echo "WARNING: ${candidate#"$root"/} holds a git repository this walk did not reach:" >&2
    echo "         ${unreached%/.git}" >&2
    echo "         It is deeper than MAX_DEPTH=$MAX_DEPTH below projects/, or under a skipped" >&2
    echo "         directory. It has NO pre-push gate. Move it up, or widen the bound." >&2
  else
    echo "note: ${candidate#"$root"/} contains no git repository — nothing to install into"
  fi
done
