#!/bin/bash
# Install the repo's local git hooks — in the root repo AND in every nested project repo.
#
# There is no CI here and no remote configured, so the agent-config validators only ever ran
# when a human remembered — which meant adding validators had limited value. This wires them
# to the one event that always happens before work is recorded.
#
# The nested variant exists because the root hook's YAML arm was unreachable: `/projects/` is
# .gitignore:3, so `git ls-files projects/` returns 0 and no staged path in the root repo can
# ever start with `projects/`. Every plan-NNN.yaml and cycle note actually commits inside its
# own nested repo, where paths are repo-relative ("docs/plan-001.yaml") — that is where the
# gate has to live. Measured before this change: 0 of 6 nested repos had a pre-commit hook,
# so 130 valid cycle notes were discipline, not enforcement.
#
# Idempotent, and it will not clobber a hook it did not write. Run from anywhere:
#   bash .agents/scripts/install-git-hooks.sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)

# Every generated hook carries this line; install_hook uses it to tell "mine, safe to replace"
# from "someone else's, hands off".
MARKER='# Generated by .agents/scripts/install-git-hooks.sh'

# ------------------------------------------------------------------
# hook bodies
#
# Read with `read -r -d ''`, not `body=$(cat <<'HOOK' … HOOK)`: macOS ships bash 3.2, whose
# `$( )` scanner mis-parses a `case … ;;` inside a quoted heredoc and dies with
# "syntax error near unexpected token `;;'" on a line it should never have parsed. `read`
# keeps the heredoc's trailing newline, so install_hook writes bodies with `printf '%s'`.
# ------------------------------------------------------------------

IFS= read -r -d '' root_body <<'HOOK' || true
#!/bin/bash
# Generated by .agents/scripts/install-git-hooks.sh — re-run that to update.
set -eu
root=$(git rev-parse --show-toplevel)

# Only guard the shared agent configuration; a commit touching nothing else skips instantly.
if git diff --cached --name-only | grep -qE '^\.(agents|claude|codex)/'; then
  echo "pre-commit: validating agent config…"
  node "$root/.agents/scripts/validate-agent-config.mjs" || {
    echo "pre-commit: agent config invalid — fix it, or commit with --no-verify only if you" >&2
    echo "            have a reason the policy itself does not cover." >&2
    exit 1
  }
  node "$root/.agents/scripts/test-agent-config.mjs" || exit 1
fi

# No docs-YAML arm here on purpose. The root repo tracks zero .yaml/.yml files
# (`git ls-files '*.yaml' '*.yml'` → 0) and `/projects/` is .gitignore:3, so the old
# `^projects/.*/docs/.*\.ya?ml$` arm could not match any staged path and never fired once.
# That check now lives in the nested-repo hook, where those files are actually staged.
HOOK

IFS= read -r -d '' nested_body <<'HOOK' || true
#!/bin/bash
# Generated by .agents/scripts/install-git-hooks.sh — re-run that to update.
#
# Nested-repo variant: the docs-YAML gate. Plan and cycle-note YAML commits HERE, never in the
# root repo — `/projects/` is .gitignore:3 up there, which is why the root hook's
# `^projects/.*/docs/.*\.ya?ml$` arm could never match: paths are repo-relative in this repo.
# The validators live in the root repo (a nested repo has no tools/docs-gen), so the root path
# is baked in at install time and they are invoked absolutely.
set -eu

root='@@ROOT@@'
gen="$root/tools/docs-gen"
cd "$(git rev-parse --show-toplevel)"

# --diff-filter=d: a commit that DELETES a plan or cycle note must not try to validate a file
# that is no longer on disk (same class of bug as the exemption check for deleted files).
staged=$(git diff --cached --name-only --diff-filter=d | grep -E '^docs/.*\.ya?ml$' || true)
[ -n "$staged" ] || exit 0

# Missing deps are an environment state, not a policy violation: skip loudly, never block.
if [ ! -d "$gen/node_modules" ]; then
  echo "pre-commit: skipping docs YAML validation — run 'npm i' in $gen to enable" >&2
  exit 0
fi

# Validate the STAGED blob, not the working-tree file: `git add` followed by an edit would
# otherwise wave broken YAML into the commit on the strength of a fixed working copy. The
# temp tree mirrors the repo-relative path so basenames survive (validate-cycle-note.mjs
# cross-checks the filename against the `cycle:` field) and error output stays readable.
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
plans=()
notes=()
while IFS= read -r f; do
  [ -n "$f" ] || continue
  copy="$tmp/$f"
  mkdir -p "$(dirname "$copy")"
  git show ":$f" > "$copy"
  case "$f" in
    docs/cycles/*)      notes+=("$copy") ;;
    docs/plan-*.yaml|docs/plan-*.yml) plans+=("$copy") ;;
    # Any other docs/*.yaml has no schema in docs-gen — nothing to check it against.
  esac
done <<< "$staged"

status=0

if [ "${#plans[@]}" -gt 0 ]; then
  echo "pre-commit: validating plan YAML…"
  node --input-type=module -e '
const [lib, tmp, ...files] = process.argv.slice(1);
const { validateFile } = await import(lib);
let bad = 0;
for (const f of files) {
  const label = f.slice(tmp.length + 1);
  try { validateFile(f, label); console.log(`  ✓ ${label}`); }
  catch (e) { bad++; console.error(`\n${e.message}\n`); }
}
process.exit(bad ? 1 : 0);
' "file://$gen/lib/validate-source.mjs" "$tmp" "${plans[@]}" || status=1
fi

if [ "${#notes[@]}" -gt 0 ]; then
  echo "pre-commit: validating cycle notes…"
  # That validator prints the path it was handed, which here is the staged-blob copy. Strip the
  # temp prefix so the report names the file the author actually has to open.
  out=$(node "$gen/scripts/validate-cycle-note.mjs" "${notes[@]}" 2>&1) || status=1
  printf '%s\n' "$out" | sed "s|$tmp/||g"
fi

if [ "$status" -ne 0 ]; then
  echo "pre-commit: docs YAML invalid — fix it, or commit with --no-verify only if you" >&2
  echo "            have a reason the policy itself does not cover." >&2
  exit 1
fi
HOOK

# The nested hook cannot find the root repo on its own, so bake the absolute path in.
nested_body=${nested_body//@@ROOT@@/$root}

# ------------------------------------------------------------------
# installer
# ------------------------------------------------------------------

# install_hook <repo-worktree> <body>
install_hook() {
  repo=$1
  body=$2

  # rev-parse --git-path resolves .git-as-a-file (worktrees, submodules) too.
  hooks=$(git -C "$repo" rev-parse --git-path hooks 2>/dev/null) || {
    echo "skipped $repo — not a git repository" >&2
    return 0
  }
  case "$hooks" in /*) ;; *) hooks="$repo/$hooks" ;; esac
  mkdir -p "$hooks"
  hook="$hooks/pre-commit"

  # This header has claimed idempotence since day one while `cat >` overwrote unconditionally,
  # so installing into a repo that already had its own pre-commit (husky, lefthook, a
  # hand-rolled linter) destroyed it silently. Only replace hooks this script generated.
  if [ -e "$hook" ] && ! grep -qF "$MARKER" "$hook" 2>/dev/null; then
    echo "skipped $hook — existing hook was not generated by this script; leaving it alone" >&2
    echo "        move or delete it and re-run to install the shared gate." >&2
    return 0
  fi

  # Both sides through command substitution so the trailing-newline handling matches.
  if [ -e "$hook" ] && [ "$(cat "$hook")" = "$(printf '%s' "$body")" ]; then
    echo "up to date $hook"
    return 0
  fi

  printf '%s' "$body" > "$hook"
  chmod +x "$hook"
  echo "installed  $hook"
}

install_hook "$root" "$root_body"

# A root-repo worktree has no projects/ at all — the nested repos live only in the primary
# checkout. Hard-failing here would red out every worktree (and every `git bisect` step that
# runs this), so absence is a skip, not an error.
if [ ! -d "$root/projects" ]; then
  echo "no $root/projects — skipping nested-repo hooks (root-only checkout or worktree)"
  exit 0
fi

found=0
for candidate in "$root"/projects/*/*; do
  [ -d "$candidate" ] || continue
  [ -e "$candidate/.git" ] || continue   # baja-dunia / northsoil-hr are not git repos
  found=$((found + 1))
  install_hook "$candidate" "$nested_body"
done

if [ "$found" -eq 0 ]; then
  echo "no nested git repositories under $root/projects"
fi
